package com.marcusrunge.mydefcon.data.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable

/**
 * Represents a single check item in the database.
 *
 * This data class is used as a Room entity to define the `checkitem` table structure.
 * It is also serializable to be easily passed between components or stored.
 *
 * @property id The unique identifier for the check item. It is auto-generated by the database.
 * @property uuid A unique string identifier for the check item, separate from the primary key.
 * @property text The descriptive text of the check item. Can be null.
 * @property isChecked Indicates whether the check item is currently checked or not.
 * @property isDeleted A flag for soft-deleting the item. If true, the item is considered deleted.
 * @property defcon The DEFCON level associated with this check item.
 * @property created The timestamp when the item was created.
 * @property updated The timestamp of the last update to the item.
 */
@Entity(tableName = "checkitem")
@kotlinx.serialization.Serializable
data class CheckItem(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    @ColumnInfo(name = "uuid") val uuid: String,
    @ColumnInfo(name = "text") var text: String?,
    @ColumnInfo(name = "is_checked") var isChecked: Boolean,
    @ColumnInfo(name = "is_deleted") var isDeleted: Boolean,
    @ColumnInfo(name = "defcon") var defcon: Int,
    @ColumnInfo(name = "created") val created: Long?,
    @ColumnInfo(name = "updated") var updated: Long
) : Serializable
